services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_HOST=mysql
      - DATABASE_NAME=talriz_db
      - DATABASE_USER=rmurray5
      - DATABASE_PASSWORD=50447880
      - DATABASE_PORT=3306
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    platform: linux/amd64
    restart: always
    environment:
      MYSQL_DATABASE: talriz_db
      MYSQL_USER: rmurray5
      MYSQL_PASSWORD: 50447880
      MYSQL_ROOT_PASSWORD: talriz
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:

