services:
  web:
    build: .
    volumes:
      - .:/root 
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=talriz.settings
    command: python manage.py runserver 0.0.0.0:8000

    depends_on:
      - db

  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: talriz_db
      
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: