services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: talriz_db
      MYSQL_USER: lejimene
      MYSQL_PASSWORD: Chestnut9121
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  web:
    build: .
    volumes:
      - .:/root
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=talriz.settings
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db

volumes:
  db_data: